### PR TITLE
Issue2

### PR DESCRIPTION
**Pull request by claireheimburg**
This pull request returns a JSON list of tracks from a specified album. The list of albums is retrieved from the Music folder using a relative address. 

To "test" this PR, you will run the code, change host to localhost, add /specific_album, then add ?album_name=Album+1 (change number to test different albums). If there are no tracks, it will output an empty list. If the album does not exist, it will print an appropriate message.

### CODE REVIEW

**Comment by Allemr** [comment]
The code is very clear and produces an appropriate JSON file (dictionary) of the album/its songs (or empty list if no tracks). If The album is not an album in the 'Music' folder, it outputs a proper message.

**Review by Allemr — DISMISSED** [review]
LGTM! Refer to my comment!

**Review by DavidBerdik — CHANGES_REQUESTED** [review]
Looks good! Just one edge case for you to fix: http://localhost:9999/specific_album?album_name=

**Review by Allemr — APPROVED** [review]
That simple change works! LGTM Claire!

**Review by DavidBerdik — APPROVED** [review]
Since this is going to be refactored (#12), I see no reason to be concerned with making changes to the code to improve its structure here. Those issues will be addressed in the follow-up ticket, and functionally, everything seems to be working properly, so, approved!

**Pull request merged**
